OS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('edu.urls'))
]

edu/urls.py
from django.conf.urls import url

from . import views

app_name = 'edu'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^contactUs/$', views.contactUs, name='contactUs'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^course/$', views.course, name='course'),
    url(r'^courses/$', views.showCourses, name='showCourse'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^panel/$', views.profile, name='panel'),
]

edu/models.py
from django.db import models
from django.contrib.auth.models import User


class Course(models.Model):
    department = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    course_number = models.CharField(max_length=200)
    group_number = models.CharField(max_length=200)
    teacher = models.CharField(max_length=200)
    start_time = models.CharField(max_length=200)
    end_time = models.CharField(max_length=200)
    day = (('1','1'), ('2','2'), ('3','3'), ('4','4'))
    first_day = models.CharField(max_length=200, choices=day)
    second_day = models.CharField(max_length=200, choices=day)

edu/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import render, redirect

from . import models

log = False


def index(request):
    global log
    return render(request, 'edu/index.html', {'log': log})


def register(request):
    global log
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        e = request.POST['email']
        username = request.POST['username']
        password = request.POST['password1']
        password2 = request.POST['password2']
        context = {"mode": 0, 'log': log}
        flag = False
        if User.objects.filter(username=username).exists():
            flag = True
        if password2 != password and flag:
            context = {"mode": 3, 'log': log}
        if password2 == password and flag:
            context = {"mode": 2, 'log': log}
        if password2 != password and not flag:
            context = {"mode": 1, 'log': log}
        if password2 == password and not flag:
            user = models.User.objects.create_user(first_name=first_name, last_name=last_name,
                                                   email=e, username=username, password=password)
            user.save()
        return render(request, 'edu/formValidator.html', context)
    else:
        return render(request, 'edu/register.html', {'log': log})


def login_view(request):
    global log
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            log = True
            login(request, user)
            return render(request, 'edu/loggedIn.html', {'log': log})
        else:
            return render(request, 'edu/loggedFailed.html', {'log': log})
    return render(request, 'edu/login.html', {'log': log})


def contactUs(request):
    global log
    if request.method == 'POST':
        subject = request.POST['title']
        message = request.POST['text']
        e = request.POST['email']
        message += e
        email(request, subject, message)
        return render(request, 'edu/contactSubmitted.html', {'log': log})
    else:
        return render(request, 'edu/contactUs.html', {'log': log})


def logout_view(request):
    global log
    log = False
    logout(request)
    return redirect('/')


def email(request, subject, message):
    email_from = settings.EMAIL_HOST_USER
    recipient_list = ['webe19lopers@gmail.com']
    send_mail(subject, message, email_from, recipient_list)


@login_required
def profile(request):
    global log
    first_name = request.user.first_name
    last_name = request.user.last_name
    username = request.user.username
    print(username)
    return render(request, 'edu/profile.html', {'log': log, 'first': first_name, 'last': last_name, 'username': username})


@login_required
def setting(request):
    if request.method == 'POST':
        first = request.POST['first_name']
        last = request.POST['last_name']
        if first:
            request.user.first_name = first
            request.user.save()
        if first:
            request.user.last_name = last
            request.user.save()
        return render(request, 'edu/setting.html', {'log': log})
    else:
        return render(request, 'edu/setting.html', {'log': log})


@login_required
def course(request):
    if request.method == 'POST':
        department = request.POST['department']
        name = request.POST['name']
        course_number = request.POST['course_number']
        group_number = request.POST['group_number']
        teacher = request.POST['teacher']
        start_time = request.POST['start_time']
        end_time = request.POST['end_time']
        first_day = request.POST['first_day']
        second_day = request.POST['second_day']
        new_course = models.Course(department=department,name=name,course_number=course_number
                                                  ,group_number=group_number,teacher=teacher,start_time=start_time
                                                  ,end_time=end_time,first_day=first_day,second_day=second_day)
        new_course.save()
        return render(request, 'edu/createCourse.html', {'log': log})
    else:
        return render(request, 'edu/createCourse.html', {'log': log})


@login_required
def showCourses(request):
    data = models.Course.objects.all()
    stu = {
        'log': log,
        "courses": data
    }
    return render(request, 'edu/showCourses.html', stu)

edu/templates/edu/contactUs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OS</title>
    <style>
/*
        :root {
           body #212121
          nav & form  #323232
            text color #0d7377
          box shadow   #14ffec
        }
*/
        *{
            padding: 0;
            margin: 0;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        body{
            font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
            background-color: #212121;
            overflow: hidden;
        }
        a{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 10px;
        }
        #navbar{
            width: 100%;
            height:50px;
            position: fixed;
            background-color: #323232;
            padding: 15px;
            float: left;
        }
        #login{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 20px;
            float: left;
        }
        #register{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 10px;
            float: left;
        }
        #homepage{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 10px;
            float: right;
        }
        form{
            margin: 100px 40%;
            width: auto;
            height: auto;
            border-radius: 15px;
            float: left;
            background-color: #323232;
            padding: 20px;
        }
        form>*{
            margin: 20px 10px;
            font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
        }
        form>label{
            color: #0d7377;
        }

        button{
            padding: 10px 30px;
            display: block;
            margin: 40px auto;
            border: 2px solid #0d7377;
            background-color: transparent;
            color: #0d7377;
            transition: .4s;
            cursor: pointer;
        }
        button:nth-of-type(1):hover{
            box-shadow: inset 0 0 0 50px #14ffec;
            color: #0d7377;
        }
















       h1 {
          font-size: 1.5em;
          text-align: center;
          color: #0d7377;
          font-weight: 100;
          text-transform: capitalize;
          letter-spacing: 4px;
        }






     input[type="text"], input[type="email"], input[type="password"] ,textarea{
          font-size: 0.9em;
          color: #fff;
          font-weight: 100;
          width: 94.5%;
          display: block;
          border: none;
          padding: 0.8em;
          border: solid 1px rgba(255, 255, 255, 0.37);
          -webkit-transition: all 0.3s cubic-bezier(0.64, 0.09, 0.08, 1);
          transition: all 0.3s cubic-bezier(0.64, 0.09, 0.08, 1);
          background: -webkit-linear-gradient(top, rgba(255, 255, 255, 0) 96%, #fff 4%);
          background: linear-gradient(to bottom, rgba(255, 255, 255, 0) 96%, #fff 4%);
          background-position: -800px 0;
          background-size: 100%;
          background-repeat: no-repeat;
}

    .text:focus, .text:valid {
          box-shadow: none;
          outline: none;
          background-position: 0 0;
}
        .text:focus::-webkit-input-placeholder, .text:valid::-webkit-input-placeholder {
  color: rgba(255, 255, 255, 0.7);
  font-size: .9em;
  -webkit-transform: translateY(-30px);
  -moz-transform: translateY(-30px);
  -o-transform: translateY(-30px);
  -ms-transform: translateY(-30px);
  transform: translateY(-30px);
  visibility: visible !important;
}
        span{
            float: right;
            margin-top: 60px;
            margin-right: 10px;
            font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
            font-size: 20px;
            color: white;
        }
    </style>
</head>
<body>
    <div id="navbar">
        {% if log == False %}
        <a href="/login" id="login">Login</a>
        {% endif %}
        {% if log == True %}
        <a href="/profile/" id="profile">Profile</a>
        <a href="/setting/" id="setting">Edit</a>
        <a href="/logout" id="logout">logout</a>
                    <a href="/panel/" id="panel">panel</a>
            {% if request.user.is_superuser %}
                    <a href="/course/" id="make_new_course">Courses</a>
                {% endif %}
            <a href="/courses/" id='courses'>show courses</a>
        {% endif %}
        <a href="/contactUs/" id="contact_us">ContactUs</a>
        <a href="/" id="homepage">HomePage</a>
    </div>
    <form action="{% url 'edu:contactUs' %}" id="contact_us_form" method="post">
        {% csrf_token %}
        <label for="">Title : </label>
        <input class="text" type="text" name="title" required>
        <br>
        <label for="">Email : </label>
        <input class="text" type="email" name="email" required>
        <br>
        <label for="">Text : </label>
        <textarea class="text" name="text" id="" cols="30" rows="10" maxlength="250" minlength="10" required></textarea>
        <button name="login">Login</button>
        
    </form>
</body>
</html>

edu/templates/edu/createCourse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OS</title>
    <style>
/*
        :root {
           body #212121
          nav & form  #323232
            text color #0d7377
          box shadow   #14ffec
        }
*/
        *{
            padding: 0;
            margin: 0;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        body{
            font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
            background-color: #212121;
            {#overflow: hidden;#}
        }
        a{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 10px;
        }
        #navbar{
            width: 100%;
            height:50px;
            position: fixed;
            background-color: #323232;
            padding: 15px;
            float: left;
        }
        #login{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 20px;
            float: left;
        }
        #register{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 10px;
            float: left;
        }
        #homepage{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 10px;
            float: right;
        }
        form{
            margin: 100px 35%;
            width: auto;
            height: auto;
            border-radius: 15px;
            float: left;
            background-color: #323232;
            padding: 20px;
        }
        form>*{
            margin: 20px 10px;
            font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
        }
        form>label{
            color: #0d7377;
        }

        button{
            padding: 10px 30px;
            display: block;
            margin: 40px auto;
            border: 2px solid #0d7377;
            background-color: transparent;
            color: #0d7377;
            transition: .4s;
            cursor: pointer;
        }
        button:nth-of-type(1):hover{
            box-shadow: inset 0 0 0 50px #14ffec;
            color: #0d7377;
        }
















       h1 {
          font-size: 1.5em;
          text-align: center;
          color: #0d7377;
          font-weight: 100;
          text-transform: capitalize;
          letter-spacing: 4px;
        }






     input[type="text"], input[type="email"], input[type="password"]  {
          font-size: 0.9em;
          color: #fff;
          font-weight: 100;
          width: 94.5%;
          display: block;
          border: none;
          padding: 0.8em;
          border: solid 1px rgba(255, 255, 255, 0.37);
          -webkit-transition: all 0.3s cubic-bezier(0.64, 0.09, 0.08, 1);
          transition: all 0.3s cubic-bezier(0.64, 0.09, 0.08, 1);
          background: -webkit-linear-gradient(top, rgba(255, 255, 255, 0) 96%, #fff 4%);
          background: linear-gradient(to bottom, rgba(255, 255, 255, 0) 96%, #fff 4%);
          background-position: -800px 0;
          background-size: 100%;
          background-repeat: no-repeat;
}

    .text:focus, .text:valid {
          box-shadow: none;
          outline: none;
          background-position: 0 0;
}
        .text:focus::-webkit-input-placeholder, .text:valid::-webkit-input-placeholder {
  color: rgba(255, 255, 255, 0.7);
  font-size: .9em;
  -webkit-transform: translateY(-30px);
  -moz-transform: translateY(-30px);
  -o-transform: translateY(-30px);
  -ms-transform: translateY(-30px);
  transform: translateY(-30px);
  visibility: visible !important;
}















        /*the container must be positioned relative:*/
.custom-select {
  position: relative;
  font-family: Arial;
}

.custom-select select {
  display: none; /*hide original SELECT element:*/
}

.select-selected {
  background-color: #19bcaf;
}

/*style the arrow inside the select element:*/
.select-selected:after {
  position: absolute;
  content: "";
  top: 14px;
  right: 10px;
  width: 0;
  height: 0;
  border: 6px solid transparent;
  border-color: #fff transparent transparent transparent;
}

/*point the arrow upwards when the select box is open (active):*/
.select-selected.select-arrow-active:after {
  border-color: transparent transparent #fff transparent;
  top: 7px;
}

/*style the items (options), including the selected item:*/
.select-items div,.select-selected {
  color: #ffffff;
  padding: 8px 16px;
  border: 1px solid transparent;
  border-color: transparent transparent rgba(0, 0, 0, 0.1) transparent;
  cursor: pointer;
  user-select: none;
}

/*style items (options):*/
.select-items {
  position: absolute;
  background-color: #14ffec;
  top: 100%;
  left: 0;
  right: 0;
  z-index: 99;
}

/*hide the items when the select box is closed:*/
.select-hide {
  display: none;
}

.select-items div:hover, .same-as-selected {
  background-color: rgba(0, 0, 0, 0.1);
}



    </style>
</head>
<body>
    <div id="navbar">
        <a href="/logout/" id="logout">LogOut</a>
        <a href="/panel/" id="panel">panel</a>
        <a href="/setting/" id="setting">Edit</a>
        <a href="/profile/" id="profile">profile</a>
        <a href="/contactUs/" id="contact_us">ContactUs</a>
        <a href="/" id="homepage">HomePage</a>
                                {% if request.user.is_superuser %}
                    <a href="/course/" id="make_new_course">Courses</a>
                {% endif %}
        <a href="/courses/" id='courses'>show courses</a>
    </div>
    <form id='make_course' action="{% url 'edu:course' %}" method="post" >
        {% csrf_token %}
        <h1>Entekhabe e Vahed</h1>

             <input class="text" type="text" name='department' required placeholder="Daneshkade">
             <br>

             <input class="text" type="text" name='name' required placeholder="Name">
             <br>

             <input class="text" type="text" name='course_number' required placeholder="Course number">
             <br>

             <input class="text" type="text" name='group_number' required placeholder="Group number">
             <br>

             <input class="text" type="text" name='teacher' required placeholder="Teacher">
             <br>

             <input class="text" type="time" name='start_time' required placeholder="Start time">
             <br>

             <input class="text" type="time" name='end_time' required placeholder="End time">
             <br>
             <label for="">First day : </label>
             <div class="custom-select" style="width:200px;">
             <select type="text" name='first_day' required>
             <option value=”0”>شنبه
             <option value=”1”>یک شنبه
             <option value=”2”>دو شنبه
             <option value=”3”>سه شنبه
             <option value=”4”>چهار شنبه
             </select>
        </div>
             <br>
             <label for="">second day</label>
        <div class="custom-select" style="width:200px;">
             <select name='second_day' >
             <option value=”0”>شنبه
             <option value=”1”>یک شنبه
             <option value=”2”>دو شنبه
             <option value=”3”>سه شنبه
             <option value=”4”>چهار شنبه
             </select>
        </div>
             <button id="sabt">Sabt</button>
    </form>
    <div id="all_courses"></div>
<script>
var x, i, j, selElmnt, a, b, c;
/*look for any elements with the class "custom-select":*/
x = document.getElementsByClassName("custom-select");
for (i = 0; i < x.length; i++) {
  selElmnt = x[i].getElementsByTagName("select")[0];
  /*for each element, create a new DIV that will act as the selected item:*/
  a = document.createElement("DIV");
  a.setAttribute("class", "select-selected");
  a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
  x[i].appendChild(a);
  /*for each element, create a new DIV that will contain the option list:*/
  b = document.createElement("DIV");
  b.setAttribute("class", "select-items select-hide");
  for (j = 1; j < selElmnt.length; j++) {
    /*for each option in the original select element,
    create a new DIV that will act as an option item:*/
    c = document.createElement("DIV");
    c.innerHTML = selElmnt.options[j].innerHTML;
    c.addEventListener("click", function(e) {
        /*when an item is clicked, update the original select box,
        and the selected item:*/
        var y, i, k, s, h;
        s = this.parentNode.parentNode.getElementsByTagName("select")[0];
        h = this.parentNode.previousSibling;
        for (i = 0; i < s.length; i++) {
          if (s.options[i].innerHTML == this.innerHTML) {
            s.selectedIndex = i;
            h.innerHTML = this.innerHTML;
            y = this.parentNode.getElementsByClassName("same-as-selected");
            for (k = 0; k < y.length; k++) {
              y[k].removeAttribute("class");
            }
            this.setAttribute("class", "same-as-selected");
            break;
          }
        }
        h.click();
    });
    b.appendChild(c);
  }
  x[i].appendChild(b);
  a.addEventListener("click", function(e) {
      /*when the select box is clicked, close any other select boxes,
      and open/close the current select box:*/
      e.stopPropagation();
      closeAllSelect(this);
      this.nextSibling.classList.toggle("select-hide");
      this.classList.toggle("select-arrow-active");
    });
}
function closeAllSelect(elmnt) {
  /*a function that will close all select boxes in the document,
  except the current select box:*/
  var x, y, i, arrNo = [];
  x = document.getElementsByClassName("select-items");
  y = document.getElementsByClassName("select-selected");
  for (i = 0; i < y.length; i++) {
    if (elmnt == y[i]) {
      arrNo.push(i)
    } else {
      y[i].classList.remove("select-arrow-active");
    }
  }
  for (i = 0; i < x.length; i++) {
    if (arrNo.indexOf(i)) {
      x[i].classList.add("select-hide");
    }
  }
}
/*if the user clicks anywhere outside the select box,
then close all select boxes:*/
document.addEventListener("click", closeAllSelect);
</script>
</body>
</html>

edu/templates/edu/formValidator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OS</title>
    <style>
/*
        :root {
           body #212121
          nav & form  #323232
            text color #0d7377
          box shadow   #14ffec
        }
*/
        *{
            padding: 0;
            margin: 0;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        body{
            font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
            background-color: #212121;
            overflow: hidden;
        }
        a{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 10px;
        }
        #navbar{
            width: 100%;
            height:50px;
            position: fixed;
            background-color: #323232;
            padding: 15px;
            float: left;
        }
        #login{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 20px;
            float: left;
        }
        #register{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 10px;
            float: left;
        }
        #homepage{
            text-transform: capitalize;
            text-decoration: none;
            color: #0d7377;
            margin-right: 10px;
            float: right;
        }
        form{
            margin: 100px 35%;
            width: auto;
            height: auto;
            border-radius: 15px;
            float: left;
            background-color: #323232;
            padding: 20px;
        }
        form>*{
            margin: 20px 10px;
            font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
        }
        form>label{
            color: #0d7377;
        }

        button{
            padding: 10px 30px;
            display: block;
            margin: 40px auto;
            border: 2px solid #0d7377;
            background-color: transparent;
            color: #0d7377;
            transition: .4s;
            cursor: pointer;
        }
        button:nth-of-type(1):hover{
            box-shadow: inset 0 0 0 50px #14ffec;
            color: #0d7377;
        }
















       h1 {
          font-size: 1.5em;
          text-align: center;
          color: #0d7377;
          font-weight: 100;
          text-transform: capitalize;
          letter-spacing: 4px;
        }






     input[type="text"], input[type="email"], input[type="password"] {
          font-size: 0.9em;
          color: #fff;
          font-weight: 100;
          width: 94.5%;
          display: block;
          border: none;
          padding: 0.8em;
          border: solid 1px rgba(255, 255, 255, 0.37);
          -webkit-transition: all 0.3s cubic-bezier(0.64, 0.09, 0.08, 1);
          transition: all 0.3s cubic-bezier(0.64, 0.09, 0.08, 1);
          background: -webkit-linear-gradient(top, rgba(255, 255, 255, 0) 96%, #fff 4%);
          background: linear-gradient(to bottom, rgba(255, 255, 255, 0) 96%, #fff 4%);
          background-position: -800px 0;
          background-size: 100%;
          background-repeat: no-repeat;
}

    .text:focus, .text:valid {
          box-shadow: none;
          outline: none;
          background-position: 0 0;
}
        .text:focus::-webkit-input-placeholder, .text:valid::-webkit-input-placeholder {
  color: rgba(255, 255, 255, 0.7);
  font-size: .9em;
  -webkit-transform: translateY(-30px);
  -moz-transform: translateY(-30px);
  -o-transform: translateY(-30px);
  -ms-transform: translateY(-30px);
  transform: translateY(-30px);
  visibility: visible !important;
}
    </style>
</head>
<body>
    <div id="navbar">
        <a href="/contactUs/" id="contact_us">ContactUs</a>
        {% if log == False %}
         <a href="/login" id="login">Login</a>
        {% endif %}
        {% if log == True %}
        <a href="/setting/" id="setting">Edit</a>
        <a href="/profile/" id="profile">Profile</a>
        <a href="/logout" id="logout">logout</a>
                    <a href="/panel/" id="panel">panel</a>
                               {% if request.user.is_superuser %}
                    <a href="/course/" id="make_new_course">Courses</a>
                {% endif %}
            <a href="/courses/" id='courses'>show courses</a>
        {% endif %}
        <a href="/register" id="register">SignUp</a>
        <a href="/" id="homepage">HomePage</a>
    </div>
    <form method="post" action="{% url 'edu:register' %}" id="register_form">
        {% csrf_token %}
       <h1>Creative SignUp Form</h1>
					<input class="text" type="text" name="first_name" placeholder="First Name" required="">
					<input class="text" type="text" name="last_name" placeholder="Last Name" required="">
					<input class="text" type="text" name="username" placeholder="Username" required="">
					<input class="text email" type="email" name="email" placeholder="Email" required="">
					<input class="text" type="password" name="password1" placeholder="Password" required="">
					<input class="text w3lpass" type="password" name="password2" placeholder="Confirm Password" required="">
        <button name="submit">Submit</button>



    </form>
</body>
</html>

edu/templates/edu/showCourses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OS</title>
    <style>
        *{
            padding: 0;
            margin: 0;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        body{
            background-color: bisque;
            overflow: hidden;
        }
        #navbar{
            width: 100%;
            height:50px;
            position: fixed;
            background-color: #ce4f4f;
            padding: 15px;
            float: left;
        }
        #login{
            text-transform: capitalize;
            text-decoration: none;
            color: white;
            margin-right: 20px;
            float: left;
        }
        #register{
            text-transform: capitalize;
            text-decoration: none;
            color: white;
            margin-right: 10px;
            float: left;
        }
        #homepage{
            text-transform: capitalize;
            text-decoration: none;
            color: white;
            margin-right: 10px;
            float: right;
        }
        a{
            text-transform: capitalize;
            text-decoration: none;
            color: white;
            margin-right: 10px;
        }
        form{
            margin: 100px 35%;
            width: 30%;
            height: 200px;
            border-radius: 15px;
            float: left;
            background-color: #ce4f4f;
            padding: 20px;
        }
        form>*{
            margin: 20px 10px;
            font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
        }
        form>label{
            color: white;
        }
        form>button{
            width: 80px;
            height: 30px;
            display: block;
            margin: 0px auto;
            font-family: Arial, "Helvetica Neue", Helvetica, sans-serif;
            background-color: white;
            outline: none;
            border: none;
        }
        span{
            display: block;
            float: right;
            margin-top: 50px;
        }
        #all_courses{
            
            margin: 100px 10%;
            width: 80%;
            height: 500px;
            border-radius: 15px;
            float: left;
            background-color: #ce4f4f;
            padding: 20px;
        }
    </style>
</head>
<body>
    <div id="navbar">
        <a href="/panel/" id="panel">panel</a>
        <a href="/logout/" id="logout">LogOut</a>
        <a href="/contactUs/" id="contact_us">ContactUs</a>
        <a href="/" id="homepage">HomePage</a>
        <a href="/profile/" id="profile">Home</a>
        <a href="/setting/" id="setting">Edit</a>
                    {% if request.user.is_superuser %}
                    <a href="/course/" id="make_new_course">Courses</a>
                {% endif %}
        <a href="/courses/" id="courses">Courses</a>
    </div>
    
    <div id="all_courses">
        {% for course in courses %}
            <div class=[{{ course.course_number }}]_[{{  course.group_number  }}]>
            <h4>{{ course.name }}</h4>
            <div>{{ course.department }}</div>
            <div>{{ course.first_day }} {{ course.second_day }}</div>
            <div>{{ course.start_time }}   {{ course.end_time }}</div>
            <div>{{ course.teacher }}</div>
        {% endfor %}
    </div>
    </div>
</body>
</html>